#!/bin/bash

#Shorthand commands
alias la="ls -a"
alias v="vim"

alias weather="curl wttr.in"

#Launching Bash Scripts
alias makehs=". $HOME/Documents/Programming/bash-scripts/MakeHaskellExecutable.sh"
alias makecpp=". $HOME/Documents/Programming/bash-scripts/MakeCPPExecutable.sh"
#alias makesfml=". $HOME/Documents/Programming/bash-scripts/<...>"
